// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jidwywpecgmcqduzmvcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppZHd5d3BlY2dtY3FkdXptdmN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMjMzOTcsImV4cCI6MjA3MTc5OTM5N30.uZoWZQTzOOYHUyycwHbPInlrO2-kNz9N8LmDGMehNRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});